name: CI/CD

on: [push, pull_request]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build .xpi package
        run: make
      - name: List files inside TabSearch.xpi
        run: unzip -l TabSearch.xpi
      - uses: actions/upload-artifact@v7
        with:
          name: TabSearch.xpi
          path: TabSearch.xpi